name: Build and SonarQube Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetch all history for accurate blame info:contentReference[oaicite:1]{index=1}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Diag
        env:
          SONAR_URL: http://sonarqube.lzaycomputing.net:9000
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "SONAR_URL: $SONAR_URL"
          echo "SONAR_HOST_URL: $SONAR_HOST_URL"
          echo "SONAR_PROJECT_KEY: $SONAR_PROJECT_KEY"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          echo "SONAR_TOKEN: $SONAR_TOKEN"

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        run: ./gradlew test jacocoTestReport sonar

